---
- name: "Demostracion de registros"
  hosts: nodos
  tasks:
    - name: "Reinicio del servicio ssh"
      service:
        name: sshd
        state: present
      register: estado_ssh

    - name: "Ping a ssh"
      command: ansible nodos -m ping
      when: estado_ssh is change
...