---
- name: "Demo de delegaciones"
  hosts: nodos
  vars:
    paquetes:
      - httpd
      - httpd-tools

    fire:
      - http
      - https

  tasks:
    - name: "Instalación de apache"
      yum:
        name: "{{ item }}"
        state: present
      loop: "{{ paquetes }}"

    - name: "Habilitar el firewall"
      firewalld:
        service: "{{ item }}"
        permanent: yes
        immediate: yes
        state: enabled
      loop: "{{ fire }}"

    - name: "Deshabilitamos selinux"
      selinux:
        state: disabled

    - name: "Creación archivo index"
      file:
        path: "/var/www/html/index.html"
        state: touch
        mode: 0755
        owner: root
        group: root

    - name: "Contenido del index"
      blockinfile: 
        path: "/var/www/html/index.html"
        block: |
          <html>
          <head>
          <title>Welcome to Example.com!</title>
          </head>
          <body>
          <h1>Success! The example.com virtual host is working!</h1>
          </body>
          </html>
    - name: "Iniciar el apache"
      service:
        name: httpd
        state: restarted
        enabled: yes

    - name: "Reinicio del nodo"
      reboot: 

    - name: "Comprobar que el servidor ha levantado"
      wait_for:
        host: "{{ inventory_hostname }}"
        port: 22
        state: started
      delegate_to: localhost

    - name: "Comprobar que el servidor escucha por el 80"
      wait_for:
        host: "{{ inventory_hostname }}"
        port: 80
        state: started
      delegate_to: localhost
...