---
- name: "Demostracion de registros"
  hosts: master
  tasks:
    - name: "Reinicio del servicio ssh"
      service:
        name: sshd
        state: restarted
      register: estado_ssh

    - name: "Ping a ssh"
      command: ansible nodos -m ping
      when: estado_ssh is change
      delegate_to: localhost
...